---

language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get remove git
  - sudo apt-get install ruby rubygems
  - sudo useradd mtester -m -d /home/mtester -s /bin/bash
  - sudo chgrp ```id -gn``` /home/mtester
  - sudo chmod g+s /home/mtester
  - sudo rm -rf /home/mtester/.gitconfig*
  - sudo rm -f /home/mtester/.gitignore-global
  - umask 002
  - gem install serverspec

install:
  - pip install ansible
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Check machine pre-test state.
  - rspec tests/spec/before_test_spec.rb

  # Check configure git by uploading files
  - ansible-playbook -i tests/inventory ./tests/playbooks/configure_from_dir.yml --syntax-check --list-tasks

  # Check role to configure gitconfig with yaml var
  - ansible-playbook -i ./tests/inventory tests/playbooks/configure_from_var.yml --connection=local --sudo
  - rspec tests/spec/configure_from_var_spec.rb
  - sudo rm -f /home/mtester/.gitconfig

  # Check role to configure git by uploading config files
  - ansible-playbook -i tests/inventory ./tests/playbooks/configure_from_url.yml --connection=local --sudo
  - rspec tests/spec/configure_from_url_spec.rb
  - sudo rm -f /home/mtester/.gitconfig

  # Check role to configure git by uploading config files
  - ansible-playbook -i tests/inventory ./tests/playbooks/configure_from_dir.yml --connection=local --sudo
  - rspec tests/spec/configure_from_dir_spec.rb
